name: better_life
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.2.1
  flutter_localizations:
    sdk: flutter
  flutter_stripe: ^9.0.0
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.2.1
  http: ^1.1.0
  intl: any
  modal_progress_hud_nsn: ^0.5.1
  pin_code_fields: ^8.0.0
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  timezone: ^0.10.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true # ✅ Turn on generation for l10n
  uses-material-design: true

  assets:
    - assets/images/splashScreen/
    - assets/images/icons/
    - assets/images/homeScreen/
